"""add gpu_samples gpu_samples_hourly usage_daily tables

Revision ID: 7f3e4acc7b2a
Revises: bb00275aebf4
Create Date: 2026-08-12 22:30:47.850397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f3e4acc7b2a'
down_revision: Union[str, None] = 'bb00275aebf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('gpu_util_pct', sa.Numeric(), nullable=True),
    sa.Column('vram_used_mib', sa.Numeric(), nullable=True),
    sa.Column('vram_total_mib', sa.Numeric(), nullable=True),
    sa.Column('temp_c', sa.Numeric(), nullable=True),
    sa.Column('power_w', sa.Numeric(), nullable=True),
    sa.Column('cpu_pct', sa.Numeric(), nullable=True),
    sa.Column('ram_used_mib', sa.Numeric(), nullable=True),
    sa.Column('active_jobs', sa.Integer(), nullable=True),
    sa.Column('queue_depth', sa.Integer(), nullable=True),
    sa.Column('telemetry_healthy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gpu_samples_sampled_at', 'gpu_samples', ['sampled_at'], unique=False)
    op.create_table('gpu_samples_hourly',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gpu_util_min', sa.Numeric(), nullable=True),
    sa.Column('gpu_util_mean', sa.Numeric(), nullable=True),
    sa.Column('gpu_util_max', sa.Numeric(), nullable=True),
    sa.Column('gpu_util_p95', sa.Numeric(), nullable=True),
    sa.Column('vram_used_mean', sa.Numeric(), nullable=True),
    sa.Column('vram_used_max', sa.Numeric(), nullable=True),
    sa.Column('temp_mean', sa.Numeric(), nullable=True),
    sa.Column('temp_max', sa.Numeric(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gpu_samples_hourly_hour', 'gpu_samples_hourly', ['hour'], unique=True)
    op.create_table('usage_daily',
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('model_alias', sa.String(length=128), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('cancelled', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('generation_ms_total', sa.BigInteger(), nullable=False),
    sa.Column('queue_wait_ms_mean', sa.Integer(), nullable=True),
    sa.Column('queue_wait_ms_p95', sa.Integer(), nullable=True),
    sa.Column('ttft_ms_mean', sa.Integer(), nullable=True),
    sa.Column('ttft_ms_p95', sa.Integer(), nullable=True),
    sa.Column('agent_sessions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('day', 'user_id', 'model_alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_daily')
    op.drop_index('ix_gpu_samples_hourly_hour', table_name='gpu_samples_hourly')
    op.drop_table('gpu_samples_hourly')
    op.drop_index('ix_gpu_samples_sampled_at', table_name='gpu_samples')
    op.drop_table('gpu_samples')
    # ### end Alembic commands ###
