"""add operating_mode table

Revision ID: bb00275aebf4
Revises: c25e4ad8bde8
Create Date: 2026-08-12 22:03:20.269668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb00275aebf4'
down_revision: Union[str, None] = 'c25e4ad8bde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operating_mode',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('switching', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operating_mode')
    # ### end Alembic commands ###
