"""add jobs table

Revision ID: c25e4ad8bde8
Revises: 81a4fd7eca01
Create Date: 2026-08-12 21:32:05.438793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c25e4ad8bde8'
down_revision: Union[str, None] = '81a4fd7eca01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=False),
    sa.Column('model_alias', sa.String(length=128), nullable=False),
    sa.Column('backend_name', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('effective_priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stream', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_wait_ms', sa.Integer(), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('error_class', sa.String(length=64), nullable=True),
    sa.Column('client_ip_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.key_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index('ix_jobs_active_status', 'jobs', ['status'], unique=False, postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.create_index('ix_jobs_alias_received_at', 'jobs', ['model_alias', 'received_at'], unique=False)
    op.create_index('ix_jobs_received_at', 'jobs', ['received_at'], unique=False)
    op.create_index('ix_jobs_user_received_at', 'jobs', ['user_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_user_received_at', table_name='jobs')
    op.drop_index('ix_jobs_received_at', table_name='jobs')
    op.drop_index('ix_jobs_alias_received_at', table_name='jobs')
    op.drop_index('ix_jobs_active_status', table_name='jobs', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING')"))
    op.drop_table('jobs')
    # ### end Alembic commands ###
